import { describe, expect, it, vi } from 'vitest';
import { renderHook } from '@testing-library/react';
import { useAppViewModels } from '../hooks/useAppViewModels';

const makeParams = (overrides = {}) => ({
  activePage: 'home',
  pagesConfig: {},
  pageSettings: {},
  editMode: false,
  isMediaPage: false,
  entities: {},
  conn: null,
  isSonosActive: false,
  activeMediaId: null,
  setActiveMediaId: vi.fn(),
  getA: vi.fn(),
  getS: vi.fn(),
  getEntityImageUrl: vi.fn(),
  callService: vi.fn(),
  savePageSetting: vi.fn(),
  gridLayout: [],
  isMobile: false,
  gridGapV: 8,
  gridGapH: 8,
  gridColCount: 4,
  isCompactCards: false,
  cardSettings: {},
  getCardSettingsKey: vi.fn(),
  hiddenCards: {},
  isCardHiddenByLogic: vi.fn(),
  renderCard: vi.fn(),
  setShowAddCardModal: vi.fn(),
  setConfigTab: vi.fn(),
  setShowConfigModal: vi.fn(),
  activeUrl: 'http://localhost',
  connected: true,
  authRef: { current: null },
  config: {},
  setConfig: vi.fn(),
  t: vi.fn((key) => key),
  language: 'en',
  setLanguage: vi.fn(),
  modals: { showConfigModal: false },
  activeVacuumId: null,
  setActiveVacuumId: vi.fn(),
  showThemeSidebar: false,
  setShowThemeSidebar: vi.fn(),
  showLayoutSidebar: false,
  setShowLayoutSidebar: vi.fn(),
  editCardSettingsKey: null,
  setEditCardSettingsKey: vi.fn(),
  configTab: 'general',
  currentTheme: 'default',
  setCurrentTheme: vi.fn(),
  bgMode: 'theme',
  setBgMode: vi.fn(),
  bgColor: '#000000',
  setBgColor: vi.fn(),
  bgGradient: '',
  setBgGradient: vi.fn(),
  bgImage: '',
  setBgImage: vi.fn(),
  cardTransparency: 0.6,
  setCardTransparency: vi.fn(),
  cardBorderOpacity: 0.2,
  setCardBorderOpacity: vi.fn(),
  cardBgColor: '#111111',
  setCardBgColor: vi.fn(),
  inactivityTimeout: 0,
  setInactivityTimeout: vi.fn(),
  setGridGapH: vi.fn(),
  setGridGapV: vi.fn(),
  gridColumns: 4,
  setGridColumns: vi.fn(),
  dynamicGridColumns: false,
  setDynamicGridColumns: vi.fn(),
  effectiveGridColumns: 4,
  cardBorderRadius: 16,
  setCardBorderRadius: vi.fn(),
  sectionSpacing: 16,
  updateSectionSpacing: vi.fn(),
  headerTitle: 'Tunet',
  headerScale: 1,
  headerSettings: {},
  updateHeaderTitle: vi.fn(),
  updateHeaderScale: vi.fn(),
  updateHeaderSettings: vi.fn(),
  showOnboarding: false,
  setShowOnboarding: vi.fn(),
  isOnboardingActive: false,
  onboardingStep: 0,
  setOnboardingStep: vi.fn(),
  onboardingUrlError: '',
  setOnboardingUrlError: vi.fn(),
  onboardingTokenError: '',
  setOnboardingTokenError: vi.fn(),
  testingConnection: false,
  testConnection: vi.fn(),
  connectionTestResult: null,
  setConnectionTestResult: vi.fn(),
  startOAuthLogin: vi.fn(),
  handleOAuthLogout: vi.fn(),
  canAdvanceOnboarding: true,
  pageDefaults: {},
  editingPage: null,
  setEditingPage: vi.fn(),
  newPageLabel: '',
  setNewPageLabel: vi.fn(),
  newPageIcon: null,
  setNewPageIcon: vi.fn(),
  createPage: vi.fn(),
  createMediaPage: vi.fn(),
  deletePage: vi.fn(),
  removeCard: vi.fn(),
  persistPageSettings: vi.fn(),
  persistConfig: vi.fn(),
  optimisticLightBrightness: {},
  setOptimisticLightBrightness: vi.fn(),
  hvacMap: {},
  fanMap: {},
  swingMap: {},
  isMediaActive: vi.fn(),
  addCardTargetPage: 'home',
  addCardType: '',
  setAddCardType: vi.fn(),
  searchTerm: '',
  setSearchTerm: vi.fn(),
  selectedEntities: [],
  setSelectedEntities: vi.fn(),
  selectedWeatherId: null,
  setSelectedWeatherId: vi.fn(),
  selectedTempId: null,
  setSelectedTempId: vi.fn(),
  selectedAndroidTVMediaId: null,
  setSelectedAndroidTVMediaId: vi.fn(),
  selectedAndroidTVRemoteId: null,
  setSelectedAndroidTVRemoteId: vi.fn(),
  selectedCostTodayId: null,
  setSelectedCostTodayId: vi.fn(),
  selectedCostMonthId: null,
  setSelectedCostMonthId: vi.fn(),
  costSelectionTarget: null,
  setCostSelectionTarget: vi.fn(),
  selectedNordpoolId: null,
  setSelectedNordpoolId: vi.fn(),
  nordpoolDecimals: 2,
  setNordpoolDecimals: vi.fn(),
  selectedSpacerVariant: 'line',
  setSelectedSpacerVariant: vi.fn(),
  onAddSelected: vi.fn(),
  getAddCardAvailableLabel: vi.fn(),
  getAddCardNoneLeftLabel: vi.fn(),
  saveCardSetting: vi.fn(),
  persistCardSettings: vi.fn(),
  customNames: {},
  saveCustomName: vi.fn(),
  persistCustomNames: vi.fn(),
  customIcons: {},
  saveCustomIcon: vi.fn(),
  persistCustomIcons: vi.fn(),
  toggleCardVisibility: vi.fn(),
  persistHiddenCards: vi.fn(),
  statusPillsConfig: {},
  saveStatusPillsConfig: vi.fn(),
  ...overrides,
});

describe('useAppViewModels', () => {
  it('returns grouped dashboard and modal models', () => {
    const { result } = renderHook(() => useAppViewModels(makeParams()));

    expect(result.current.dashboardGridPage.activePage).toBe('home');
    expect(result.current.dashboardGridGrid.gridColCount).toBe(4);
    expect(result.current.modalManagerCore.language).toBe('en');
    expect(result.current.modalManagerState.showConfigModal).toBe(false);
    expect(result.current.modalManagerCardConfig.statusPillsConfig).toEqual({});
  });

  it('updates dashboard page model when activePage changes', () => {
    const { result, rerender } = renderHook((props) => useAppViewModels(props), {
      initialProps: makeParams({ activePage: 'home' }),
    });

    expect(result.current.dashboardGridPage.activePage).toBe('home');

    rerender(makeParams({ activePage: 'livingroom' }));
    expect(result.current.dashboardGridPage.activePage).toBe('livingroom');
  });
});
