export function buildProfilesContextSetters({
  page,
  layout,
  appearance,
  setLanguage,
}) {
  return {
    persistConfig: page.persistConfig,
    persistCardSettings: page.persistCardSettings,
    persistPageSettings: page.persistPageSettings,
    persistCustomNames: page.persistCustomNames,
    persistCustomIcons: page.persistCustomIcons,
    persistHiddenCards: page.persistHiddenCards,
    setGridColumns: layout.setGridColumns,
    setGridGapH: layout.setGridGapH,
    setGridGapV: layout.setGridGapV,
    setCardBorderRadius: layout.setCardBorderRadius,
    updateHeaderScale: layout.updateHeaderScale,
    updateHeaderTitle: layout.updateHeaderTitle,
    updateHeaderSettings: layout.updateHeaderSettings,
    updateSectionSpacing: layout.updateSectionSpacing,
    saveStatusPillsConfig: page.saveStatusPillsConfig,
    setCurrentTheme: appearance.setCurrentTheme,
    setLanguage,
    setBgMode: appearance.setBgMode,
    setBgColor: appearance.setBgColor,
    setBgGradient: appearance.setBgGradient,
    setBgImage: appearance.setBgImage,
    setCardTransparency: appearance.setCardTransparency,
    setCardBorderOpacity: appearance.setCardBorderOpacity,
    setCardBgColor: appearance.setCardBgColor,
    setInactivityTimeout: appearance.setInactivityTimeout,
  };
}
